- name: Restart PHP8.0-FPM
  become: yes
  service:
    name: php8.0-fpm
    state: restarted
  tags: always

- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted
  tags: always
